# Generated by Django 5.2.4 on 2025-07-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_shipmen_dd2271_idx',
            old_name='chat_convers_shipmen_123456',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_sender__9657e8_idx',
            old_name='chat_convers_sender__123456',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_is_acti_72f866_idx',
            old_name='chat_convers_is_acti_123456',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_message_convers_123456',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__c4389c_idx',
            old_name='chat_message_sender_123456',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_is_read_872c73_idx',
            old_name='chat_message_is_read_123456',
        ),
    ]
