# Generated by Django 5.2.4 on 2025-07-27 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notification_enabled', models.BooleanField(default=True)),
                ('min_rating', models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('preferred_cities', models.JSONField(default=list)),
                ('blacklisted_users', models.JSONField(default=list)),
                ('response_time_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(168)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matching preferences',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.CharField(default='1.0', max_length=20)),
                ('matching_factors', models.JSONField(default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='shipments.shipment')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='trips.trip')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'indexes': [models.Index(fields=['shipment', 'status'], name='matching_ma_shipmen_97f04e_idx'), models.Index(fields=['trip', 'status'], name='matching_ma_trip_id_ad2210_idx'), models.Index(fields=['compatibility_score'], name='matching_ma_compati_a984a6_idx'), models.Index(fields=['expires_at'], name='matching_ma_expires_fc79f4_idx')],
                'unique_together': {('shipment', 'trip')},
            },
        ),
    ]
