# Generated by Django 5.2.4 on 2025-07-27 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('flexible_dates', models.BooleanField(default=False)),
                ('flexibility_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)])),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('remaining_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_packages', models.PositiveIntegerField(default=1)),
                ('remaining_packages', models.PositiveIntegerField()),
                ('accepted_package_types', models.JSONField(default=list)),
                ('min_price_per_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('accepts_fragile', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_ticket', models.FileField(blank=True, upload_to='trip_documents/flight_tickets/')),
                ('passport_copy', models.FileField(blank=True, upload_to='trip_documents/passports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trips.trip')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['traveler', 'status'], name='trips_trip_travele_001d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['origin_city', 'destination_city'], name='trips_trip_origin__a605f8_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_date', 'arrival_date'], name='trips_trip_departu_d22bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['remaining_weight', 'remaining_packages'], name='trips_trip_remaini_0ab542_idx'),
        ),
    ]
