# Generated by Django 5.2.4 on 2025-08-14 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
            },
        ),
        migrations.AlterModelOptions(
            name="tripdocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Document de trajet",
                "verbose_name_plural": "Documents de trajet",
            },
        ),
        migrations.AddField(
            model_name="tripdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("flight_ticket", "Billet d'avion"),
                    ("passport_copy", "Copie du passeport"),
                    ("visa", "Visa"),
                    ("boarding_pass", "Carte d'embarquement"),
                    ("travel_insurance", "Assurance voyage"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tripdocument",
            unique_together={("trip", "document_type")},
        ),
        migrations.AddField(
            model_name="tripdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="trip_documents/",
                verbose_name="Fichier",
            ),
        ),
        migrations.AddField(
            model_name="tripdocument",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Document vérifié"),
        ),
        migrations.AddField(
            model_name="tripdocument",
            name="verification_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de vérification"
            ),
        ),
        migrations.AddField(
            model_name="tripdocument",
            name="verification_notes",
            field=models.TextField(blank=True, verbose_name="Notes de vérification"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="accepted_package_types",
            field=models.JSONField(
                default=list,
                help_text="Liste des types de colis acceptés par le voyageur",
                verbose_name="Types de colis acceptés",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="accepts_fragile",
            field=models.BooleanField(
                default=False,
                help_text="Le voyageur accepte de transporter des colis fragiles",
                verbose_name="Accepte les colis fragiles",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="arrival_date",
            field=models.DateTimeField(
                help_text="Date et heure d'arrivée", verbose_name="Date d'arrivée"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_date",
            field=models.DateTimeField(
                help_text="Date et heure de départ", verbose_name="Date de départ"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination_city",
            field=models.CharField(
                help_text="Ville d'arrivée du voyageur",
                max_length=100,
                verbose_name="Ville de destination",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination_country",
            field=models.CharField(
                help_text="Pays d'arrivée",
                max_length=100,
                verbose_name="Pays de destination",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="flexibility_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre de jours de flexibilité (0-30)",
                validators=[django.core.validators.MaxValueValidator(30)],
                verbose_name="Jours de flexibilité",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="flexible_dates",
            field=models.BooleanField(
                default=False,
                help_text="Le voyageur accepte des dates flexibles",
                verbose_name="Dates flexibles",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Le trajet a été vérifié par l'administration",
                verbose_name="Trajet vérifié",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="max_packages",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Nombre maximum de colis que le voyageur peut transporter",
                verbose_name="Nombre maximum de colis",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="max_weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Poids maximum en kg que le voyageur peut transporter",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Poids maximum",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="min_price_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix minimum demandé par kg de transport",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Prix minimum par kg",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notes additionnelles du voyageur",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="origin_city",
            field=models.CharField(
                help_text="Ville de départ du voyageur",
                max_length=100,
                verbose_name="Ville d'origine",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="origin_country",
            field=models.CharField(
                default="Algeria",
                help_text="Pays de départ (par défaut Algérie)",
                max_length=100,
                verbose_name="Pays d'origine",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="remaining_packages",
            field=models.PositiveIntegerField(
                help_text="Nombre de colis restants que le voyageur peut transporter",
                verbose_name="Colis restants",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="remaining_weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Poids restant disponible en kg",
                max_digits=8,
                verbose_name="Poids restant",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("active", "Actif"),
                    ("in_progress", "En cours"),
                    ("completed", "Terminé"),
                    ("cancelled", "Annulé"),
                    ("expired", "Expiré"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut du trajet",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Voyageur",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="tripdocument",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="trips.trip",
                verbose_name="Trajet",
            ),
        ),
        migrations.AlterField(
            model_name="tripdocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["status", "is_verified"], name="trips_trip_status_ed11e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["destination_country", "departure_date"],
                name="trips_trip_destina_2fbabb_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="tripdocument",
            name="flight_ticket",
        ),
        migrations.RemoveField(
            model_name="tripdocument",
            name="passport_copy",
        ),
    ]
