# Generated by Django 5.2.4 on 2025-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_add_document_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="remaining_packages",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre de colis restants que le voyageur peut transporter",
                null=True,
                verbose_name="Colis restants",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="remaining_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Poids restant disponible en kg",
                max_digits=8,
                null=True,
                verbose_name="Poids restant",
            ),
        ),
    ]
