# Generated by Django 5.2.4 on 2025-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_alter_trip_remaining_packages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="destination_address",
            field=models.TextField(
                blank=True,
                help_text="Adresse complète d'arrivée",
                verbose_name="Adresse de destination",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="origin_address",
            field=models.TextField(
                blank=True,
                help_text="Adresse complète de départ",
                verbose_name="Adresse d'origine",
            ),
        ),
    ]
