# Generated by Django 5.2.4 on 2025-08-14 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0006_alter_user_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du workflow"),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("standard", "Workflow standard"),
                            ("premium", "Workflow premium"),
                            ("express", "Workflow express"),
                            ("manual", "Workflow manuel uniquement"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Workflow actif"),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Liste des étapes du workflow"
                    ),
                ),
                (
                    "auto_approval_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=90.0,
                        help_text="Seuil d'approbation automatique",
                        max_digits=5,
                    ),
                ),
                (
                    "requires_manual_review",
                    models.BooleanField(
                        default=False, verbose_name="Nécessite vérification manuelle"
                    ),
                ),
                (
                    "max_processing_time",
                    models.DurationField(
                        blank=True, help_text="Temps maximum de traitement", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description du workflow"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow de vérification",
                "verbose_name_plural": "Workflows de vérification",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du template"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passeport"),
                            ("national_id", "Carte d'identité nationale"),
                            ("flight_ticket", "Billet d'avion"),
                            ("address_proof", "Justificatif de domicile"),
                        ],
                        max_length=25,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("DZ", "Algérie"),
                            ("FR", "France"),
                            ("US", "États-Unis"),
                            ("GB", "Royaume-Uni"),
                            ("DE", "Allemagne"),
                            ("IT", "Italie"),
                            ("ES", "Espagne"),
                            ("CA", "Canada"),
                            ("AU", "Australie"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=5,
                        verbose_name="Pays d'origine",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Template actif"),
                ),
                (
                    "sample_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="document_templates/",
                        verbose_name="Image d'exemple",
                    ),
                ),
                (
                    "validation_zones",
                    models.JSONField(
                        default=dict, help_text="Zones de validation sur le document"
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        default=list, help_text="Champs requis pour ce type de document"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description du template"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template de document",
                "verbose_name_plural": "Templates de documents",
                "ordering": ["document_type", "country", "name"],
                "unique_together": {("document_type", "country", "name")},
            },
        ),
        migrations.CreateModel(
            name="DocumentValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la règle"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passeport"),
                            ("national_id", "Carte d'identité nationale"),
                            ("flight_ticket", "Billet d'avion"),
                            ("address_proof", "Justificatif de domicile"),
                            ("driver_license", "Permis de conduire"),
                            ("birth_certificate", "Acte de naissance"),
                            ("marriage_certificate", "Acte de mariage"),
                        ],
                        max_length=25,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("ocr_extraction", "Extraction OCR"),
                            ("format_validation", "Validation de format"),
                            ("expiry_check", "Vérification d'expiration"),
                            ("fraud_detection", "Détection de fraude"),
                            ("data_consistency", "Cohérence des données"),
                            ("image_quality", "Qualité d'image"),
                        ],
                        max_length=25,
                        verbose_name="Type de validation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Règle active"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Priorité d'exécution"
                    ),
                ),
                (
                    "validation_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration de la règle de validation",
                    ),
                ),
                (
                    "threshold_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Score seuil pour validation",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description de la règle"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes additionnelles"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Règle de validation",
                "verbose_name_plural": "Règles de validation",
                "ordering": ["priority", "name"],
                "unique_together": {("document_type", "validation_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours de traitement"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            (
                                "requires_manual_review",
                                "Nécessite vérification manuelle",
                            ),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("automatic", "Vérification automatique"),
                            ("manual", "Vérification manuelle"),
                            ("hybrid", "Vérification hybride"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "ocr_data",
                    models.JSONField(
                        default=dict, help_text="Données extraites par OCR"
                    ),
                ),
                (
                    "validation_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score de validation (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fraud_detection_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score de détection de fraude (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verification_duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="users.userdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification de document",
                "verbose_name_plural": "Vérifications de documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("success", "Succès"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(verbose_name="Message du log")),
                (
                    "details",
                    models.JSONField(default=dict, help_text="Détails additionnels"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="verification.documentverification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de vérification",
                "verbose_name_plural": "Logs de vérification",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["user", "status"], name="verificatio_user_id_97b61d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["document", "status"], name="verificatio_documen_dda945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["verification_method"], name="verificatio_verific_8b276b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["created_at"], name="verificatio_created_3c2b11_idx"
            ),
        ),
    ]
