# Generated by Django 5.2.4 on 2025-07-28 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('receipt', 'Reçu'), ('contract', 'Contrat'), ('custom', 'Document personnalisé')], max_length=20, verbose_name='Type de document')),
                ('template_file', models.FileField(upload_to='document_templates/', verbose_name='Fichier template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Template de document',
                'verbose_name_plural': 'Templates de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID du document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('receipt', 'Reçu'), ('contract', 'Contrat'), ('custom', 'Document personnalisé')], max_length=20, verbose_name='Type de document')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('generated', 'Généré'), ('sent', 'Envoyé'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('content_data', models.JSONField(default=dict, verbose_name='Données du contenu')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_documents/', verbose_name='Fichier généré')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Généré le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('client_address', models.TextField(verbose_name='Adresse du client')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant des taxes')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payée')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('payment_date', models.DateTimeField(verbose_name='Date de paiement')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Méthode de paiement')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
            },
        ),
    ]
