# Generated by Django 5.2.4 on 2025-07-27 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('traveler_earning', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='shipments.shipment')),
            ],
            options={
                'indexes': [models.Index(fields=['shipment'], name='payments_co_shipmen_911d6e_idx'), models.Index(fields=['created_at'], name='payments_co_created_c9a21e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('payment', 'Paiement'), ('refund', 'Remboursement'), ('commission', 'Commission'), ('earning', 'Gains'), ('transfer', 'Transfert')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('external_payment_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('wallet', 'Portefeuille'), ('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('chargily', 'Chargily Pay')], max_length=20)),
                ('payment_gateway', models.CharField(blank=True, choices=[('chargily', 'Chargily Pay'), ('stripe', 'Stripe'), ('manual', 'Manuel')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='payments.transaction')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shipments.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='payments_tr_user_id_cabadd_idx'), models.Index(fields=['shipment'], name='payments_tr_shipmen_0cbe76_idx'), models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'), models.Index(fields=['transaction_id'], name='payments_tr_transac_e96a4f_idx'), models.Index(fields=['created_at'], name='payments_tr_created_02ae92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='payments_wa_user_id_cd1a1f_idx'), models.Index(fields=['balance'], name='payments_wa_balance_faa9d9_idx')],
            },
        ),
    ]
