# Generated by Django 5.2.4 on 2025-08-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("shipments", "0004_deliveryotp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("card", "Carte bancaire"),
                            ("cib", "CIB"),
                            ("eddahabia", "Eddahabia"),
                            ("cash", "Espèces"),
                            ("bank_transfer", "Virement bancaire"),
                            ("chargily", "Chargily Pay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_online",
                    models.BooleanField(
                        default=True, help_text="Paiement en ligne ou au bureau"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=10
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Frais de traitement en %",
                        max_digits=5,
                    ),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Frais fixes",
                        max_digits=10,
                    ),
                ),
                (
                    "office_locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des bureaux disponibles",
                    ),
                ),
                (
                    "office_hours",
                    models.CharField(
                        blank=True, help_text="Heures d'ouverture", max_length=200
                    ),
                ),
                (
                    "office_instructions",
                    models.TextField(
                        blank=True, help_text="Instructions pour paiement au bureau"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_holder_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cib", "CIB"),
                    ("eddahabia", "Eddahabia"),
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cash_payment_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_payments_confirmed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cash_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Date de paiement en espèces", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cash_payment_location",
            field=models.CharField(
                blank=True, help_text="Bureau de paiement", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cash_payment_reference",
            field=models.CharField(
                blank=True, help_text="Référence de paiement en espèces", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_gateway",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cib", "CIB"),
                    ("eddahabia", "Eddahabia"),
                    ("chargily", "Chargily Pay"),
                    ("stripe", "Stripe"),
                    ("manual", "Manuel (Bureau)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wallet", "Portefeuille"),
                    ("card", "Carte bancaire"),
                    ("cib", "CIB"),
                    ("eddahabia", "Eddahabia"),
                    ("cash", "Espèces"),
                    ("bank_transfer", "Virement bancaire"),
                    ("chargily", "Chargily Pay"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["payment_method"], name="payments_tr_payment_cf71a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["card_type"], name="payments_tr_card_ty_1df07b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["method_type"], name="payments_pa_method__c479ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["is_active"], name="payments_pa_is_acti_c01362_idx"
            ),
        ),
    ]
