# Generated by Django 5.2.4 on 2025-07-27 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('electronics', 'Électronique'), ('clothing', 'Vêtements'), ('food', 'Nourriture'), ('medicine', 'Médicaments'), ('fragile', 'Fragile'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('dimensions', models.JSONField(default=dict)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_fragile', models.BooleanField(default=False)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_address', models.TextField()),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_pickup_date', models.DateTimeField()),
                ('max_delivery_date', models.DateTimeField()),
                ('urgency', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('matched', 'Associé'), ('in_transit', 'En transit'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('lost', 'Perdu')], default='draft', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('wallet', 'Portefeuille'), ('card', 'Carte bancaire'), ('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire')], max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('insurance_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_shipments', to='trips.trip')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Créé'), ('pending_pickup', 'En attente de ramassage'), ('picked_up', 'Ramassé'), ('in_transit', 'En transit'), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('failed_delivery', 'Livraison échouée'), ('returned', 'Retourné')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sender', 'status'], name='shipments_s_sender__066634_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin_city', 'destination_city'], name='shipments_s_origin__f277ce_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['preferred_pickup_date', 'max_delivery_date'], name='shipments_s_preferr_89f3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['shipment', 'timestamp'], name='shipments_s_shipmen_78bcec_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['status', 'timestamp'], name='shipments_s_status_30d897_idx'),
        ),
    ]
