# Generated by Django 5.2.4 on 2025-08-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_package_shipmentdocument_shipmentrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='event_type',
            field=models.CharField(choices=[('created', 'Créé'), ('pending_pickup', 'En attente de ramassage'), ('picked_up', 'Ramassé'), ('in_transit', 'En transit'), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('failed_delivery', 'Livraison échouée'), ('returned', 'Retourné')], default='created', max_length=20),
        ),
    ]
