# Generated by Django 5.2.4 on 2025-08-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0003_shipment_delivery_date_shipment_delivery_otp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        help_text="Code OTP à 6 chiffres pour la livraison",
                        max_length=6,
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        help_text="Numéro de téléphone du destinataire", max_length=20
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(help_text="Nom du destinataire", max_length=200),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de génération de l'OTP"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Date d'expiration de l'OTP (24h après génération)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="OTP utilisé pour confirmer la livraison",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de vérification de l'OTP", null=True
                    ),
                ),
                (
                    "sms_sent",
                    models.BooleanField(
                        default=False, help_text="SMS envoyé au destinataire"
                    ),
                ),
                (
                    "sms_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Date d'envoi du SMS", null=True
                    ),
                ),
                (
                    "sms_delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyé"),
                            ("delivered", "Livré"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        help_text="Statut de livraison du SMS",
                        max_length=20,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        help_text="Voyageur qui a généré l'OTP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_otps_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_otps",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Voyageur qui a vérifié l'OTP",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_otps_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP de livraison",
                "verbose_name_plural": "OTP de livraison",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "is_used", "expires_at"],
                        name="shipments_d_shipmen_63b792_idx",
                    ),
                    models.Index(
                        fields=["recipient_phone", "is_used"],
                        name="shipments_d_recipie_5e3959_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="shipments_d_created_69aca0_idx"
                    ),
                ],
            },
        ),
    ]
