# Generated by Django 5.2.4 on 2025-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0004_deliveryotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="delivery_notes",
            field=models.TextField(blank=True, help_text="Notes sur la livraison"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="recipient_signature",
            field=models.CharField(
                blank=True, help_text="Signature du destinataire", max_length=200
            ),
        ),
    ]
