# Generated by Django 5.2.4 on 2025-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0005_shipment_delivery_notes_shipment_recipient_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="delivery_otp",
            field=models.CharField(
                blank=True,
                help_text="OBSOLÈTE - Code OTP livraison (remplacé par DeliveryOTP)",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="otp_code",
            field=models.CharField(
                blank=True,
                help_text="OBSOLÈTE - Code OTP ramassage (remplacé par DeliveryOTP)",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="otp_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="OBSOLÈTE - Date génération OTP (remplacé par DeliveryOTP)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("pending", "En attente"),
                    ("matched", "Associé"),
                    ("in_transit", "En transit"),
                    ("out_for_delivery", "En livraison"),
                    ("delivered", "Livré"),
                    ("cancelled", "Annulé"),
                    ("lost", "Perdu"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
