# Generated by Django 5.2.4 on 2025-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipments", "0006_update_obsolete_otp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="origin_country",
            field=models.CharField(default="Algeria", max_length=100),
        ),
    ]
