# Generated by Django 4.2.7 on 2024-01-15 22:55:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_fix_user_agent_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='session_id',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='ID de session'),
        ),
    ]
