# Generated by Django 5.2.4 on 2025-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otpcode_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document utilisateur', 'verbose_name_plural': 'Documents utilisateur'},
        ),
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de commission en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_sender',
            field=models.BooleanField(default=False, help_text='Expéditeur actif avec envois en cours'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_traveler',
            field=models.BooleanField(default=False, help_text='Voyageur actif avec trajets en cours'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Solde du portefeuille', max_digits=10),
        ),
    ]
