# Generated by Django 5.2.4 on 2025-08-11 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_otpcode_code_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="La note ne peut pas être négative"
                    ),
                    django.core.validators.MaxValueValidator(
                        9.99, message="La note ne peut pas dépasser 9.99"
                    ),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["phone_number", "is_used", "expires_at"],
                name="users_otpco_phone_n_00243d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["created_at"], name="users_otpco_created_e8289c_idx"
            ),
        ),
    ]
