# Generated by Django 5.2.4 on 2025-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="code",
            field=models.CharField(max_length=80),
        ),
    ]
