# Generated by Django 5.2.4 on 2025-08-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_otpcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("passport", "Passeport"),
                    ("national_id", "Carte d'identité nationale"),
                    ("id_card", "Carte d'identité"),
                    ("driver_license", "Permis de conduire"),
                    ("flight_ticket", "Billet d'avion"),
                    ("address_proof", "Justificatif de domicile"),
                    ("birth_certificate", "Acte de naissance"),
                    ("marriage_certificate", "Acte de mariage"),
                    ("other", "Autre document"),
                ],
                max_length=20,
            ),
        ),
    ]
