name: Deploy backend to Docker Hub (Central)

on:
  repository_dispatch:
    types: [run-central-ci]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kleerlogistics
          password: B3V59LwyvJgG2yt  # Hardcoded as you requested

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kleerlogistics/backend-app:latest
